//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.LeaveSubmissionTable = new HashSet<LeaveSubmissionTable>();
        }
    
        public int id { get; set; }
        public string EmployeeID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> Genderid { get; set; }
        public Nullable<int> RoleTypeId { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> Vacation { get; set; }
        public Nullable<int> Sick { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Personal { get; set; }
        public string Passwords { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveSubmissionTable> LeaveSubmissionTable { get; set; }
        public virtual RoleTypes RoleTypes { get; set; }
    }
}
