//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployees
    {
        public int id { get; set; }
        public string EmployeeID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string gender { get; set; }
        public string roles { get; set; }
        public string Passwords { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> Vacation { get; set; }
        public Nullable<int> Sick { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Personal { get; set; }
    }
}
